// Regenerates worker/prices.js (the server-side price table, keyed by
// `${product.id}_${dose}`) from the catalog in src/data/products.js.
// Run after any price/variant change:  node scripts/gen-prices.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { ALL_PRODUCTS } from '../src/data/products.js';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../worker/prices.js');

const lines = [];
for (const p of ALL_PRODUCTS) {
  for (const v of p.variants || []) {
    const key = `${p.id}_${v.dose}`;
    const price = v.price == null ? 'null' : v.price;
    lines.push(`  ${JSON.stringify(key)}: { price: ${price} },`);
  }
}

const body = `// AUTO-DERIVED server-side price table — source of truth for /api/order.
// Generated by scripts/gen-prices.mjs from src/data/products.js — do not edit by hand.
export const PRICES = {
${lines.join('\n')}
};

export function priceFor(productId){
  const e = PRICES[productId];
  return e && typeof e.price === 'number' ? e : null;
}
`;

writeFileSync(out, body);
console.log(`wrote ${lines.length} SKUs to worker/prices.js`);
